apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
      # annotations: 
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/port: "8080"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres-0.postgres.default.svc.cluster.local 5432; do
                echo "Waiting for postgres to be ready..."
                sleep 2
              done
      containers:
        - name: inventory
          image: inventory-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-0.postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: hari123
            - name: DB_NAME
              value: inventory_db
            - name: APP_ENV
              value: production
